runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on

handlers:
# The endpoints handler must be mapped to /_ah/spi.
# Apps send requests to /_ah/api, but the endpoints service handles mapping
# those requests to /_ah/spi.
- url: /_ah/spi/.*
  script: api.api

- url: /scss
  static_dir: scss

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: webapp.app

libraries:
- name: pycrypto
  version: 2.6
- name: endpoints
  version: 1.0